### ISSUE TITLE
Transformer error on unknown sandbox.

### ISSUE THREAD

**Issue by rayk** [BlackHC/dart_repl#1]
**on Pub Upgrade**
```
A transformer imported unknown package "dart_repl_sandbox" (in "package:dart_repl_sandbox/isolate_messages.dart").
```

**on Execution**
```
dart --enable-vm-service bin/dart_repl
Observatory listening on http://127.0.0.1:8181/
Unhandled exception:
Could not load "file:///Users/rayk/Projects/uncertapp/bin/dart_repl": FileSystemException: Cannot open file, path = '/Users/rayk/Projects/uncertapp/bin/dart_repl' (OS Error: No such file or directory, errno = 2)
null
```

- _Have check dart_repl did install to the dir OK._

**Set in dev_dependencies**
 dart_repl: '0.9.0'

**The Vm**
Dart VM version: 1.21.1 (Fri Jan 13 01:40:43 2017) on "macos_x64"

**What is the package file**

analyzer:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/analyzer-0.29.3/lib/
args:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/args-0.13.7/lib/
async:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/async-1.11.3/lib/
barback:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/barback-0.15.2+9/lib/
boolean_selector:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.2/lib/
browser:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/browser-0.10.0+2/lib/
build:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/build-0.6.3/lib/
build_barback:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/build_barback-0.0.3/lib/
build_runner:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/build_runner-0.1.1/lib/
built_collection:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/built_collection-1.3.0/lib/
built_value:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/built_value-0.5.0/lib/
built_value_generator:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/built_value_generator-0.5.0/lib/
charcode:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.1/lib/
cli_util:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/cli_util-0.0.1+2/lib/
code_transformers:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/code_transformers-0.5.0+2/lib/
collection:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/collection-1.13.0/lib/
convert:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/convert-2.0.1/lib/
crypto:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/crypto-2.0.1/lib/
csslib:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/csslib-0.13.2+2/lib/
dart_repl:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/dart_repl-0.9.0/lib/
dart_style:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/dart_style-0.2.14/lib/
dart_to_js_script_rewriter:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/dart_to_js_script_rewriter-1.0.2/lib/
glob:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/glob-1.1.3/lib/
html:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/html-0.13.1/lib/
http:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/http-0.11.3+9/lib/
http_multi_server:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/http_multi_server-2.0.3/lib/
http_parser:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.1/lib/
isolate:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/isolate-0.2.3/lib/
json_rpc_2:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/json_rpc_2-2.0.3/lib/
logging:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/logging-0.11.3+1/lib/
matcher:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.0+2/lib/
meta:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/meta-1.0.4/lib/
mime:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/mime-0.9.3/lib/
package_config:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/package_config-1.0.0/lib/
package_resolver:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/package_resolver-1.0.2/lib/
path:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/path-1.4.1/lib/
plugin:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/plugin-0.2.0/lib/
pool:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/pool-1.2.4/lib/
pub_semver:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/pub_semver-1.3.2/lib/
quiver:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/quiver-0.23.0/lib/
quiver_hashcode:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/quiver_hashcode-1.0.0/lib/
sass:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/sass-1.0.0-alpha.7/lib/
shelf:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/shelf-0.6.7+2/lib/
shelf_packages_handler:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/shelf_packages_handler-1.0.0/lib/
shelf_static:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/shelf_static-0.2.4/lib/
shelf_web_socket:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/shelf_web_socket-0.2.1/lib/
simple_sass_transformer:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/simple_sass_transformer-0.0.1+1/lib/
source_gen:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/source_gen-0.5.3+2/lib/
source_map_stack_trace:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/source_map_stack_trace-1.1.4/lib/
source_maps:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/source_maps-0.10.2/lib/
source_span:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/source_span-1.3.1/lib/
stack_trace:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.7.0/lib/
stream_channel:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/stream_channel-1.5.0/lib/
string_scanner:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.1/lib/
test:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/test-0.12.18+1/lib/
tuple:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/tuple-1.0.1/lib/
typed_data:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/typed_data-1.1.3/lib/
utf:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+3/lib/
vm_service_client:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/vm_service_client-0.2.3/lib/
watcher:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.7+3/lib/
web_socket_channel:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/web_socket_channel-1.0.4/lib/
when:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/when-0.2.0/lib/
which:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/which-0.1.3/lib/
yaml:file:///Users/rayk/.pub-cache/hosted/pub.dartlang.org/yaml-2.1.12/lib/
uncertaintyApp:lib/

**What is in the Yaml**

--cut

dependencies:
  quiver: any
  meta: ^1.0.4
  built_collection: ^1.0.0
  built_value: ^0.5.0

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  build: '0.6.3'
  build_barback: any
  build_runner: any
  built_value_generator: any
  dart_repl: '0.9.0'
  dart_to_js_script_rewriter: '1.0.2'
  simple_sass_transformer: '0.0.1+1'
  source_gen: '>=0.5.0+03 <0.6.0'
  test: '>=0.12.0 <0.13.0'

dependency_overrides:

transformers:
- dart_to_js_script_rewriter
- simple_sass_transformer

**Comment by BlackHC** [comment]
Hello rayk,

thanks for trying the package! I think you're the first one to run it. I haven't tried to set it up this way. I was just running bin/repl.dart from my git checkout. I'll see what I can do.

Thanks,
 Andreas

**Comment by BlackHC** [comment]
This should be fixed now. Please run pub get/upgrade (new version is 0.9.2) and try again :).
Please re-open in case I missed something.

Thanks,
 Andreas
